version: '3.8'

services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=toor
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
