--aufgabe 6.1
DROP TYPE SG_TABLE_TYPE;
DROP TYPE SG;

CREATE OR REPLACE NONEDITIONABLE TYPE SG AS OBJECT (
  SBEZ      VARCHAR2(5),
  RSTUDZEIT NUMBER,
  AKADG     VARCHAR2(10)
);
/

CREATE OR REPLACE NONEDITIONABLE TYPE SG_TABLE_TYPE AS TABLE OF SG;
/

CREATE TABLE HOCHSCHULE (
  FBEZ       VARCHAR2(5),
  ADRESSE    VARCHAR2(50),
  STUDGAENGE SG_TABLE_TYPE
)
NESTED TABLE STUDGAENGE STORE AS STUDGAENGE_NT;
